# Generated by Django 4.0.1 on 2022-01-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.TextField()),
                ('emp_emial', models.TextField()),
                ('emp_mobile', models.TextField()),
                ('emp_address', models.TextField()),
            ],
        ),
    ]
